name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "source/receiver_logic/*.h,source/receiver_logic/*.cpp,source/rrv_plugin/*.h,source/rrv_plugin/*.cpp"